### ISSUE TITLE
wrong tokenization for the first word

### ISSUE THREAD

**Issue by bnicenboim** [kanishkamisra/minicons#2]
When I try to get probabilities for  "Banana is a word." the tokenization is messed up:
 ['Ban', 'ana', 'Ġis', 'Ġa', 'Ġword', '.'] 

(Do you know why there is no G for "Ban" , "ana"?)

If I include an initial space, it works fine: ['ĠBanana', 'Ġis', 'Ġa', 'Ġword', '.']

**Comment by bnicenboim** [comment]
Also if I add a space at the beginning of a sentence that works fine, the tokenization is the same as if I didn't but logprobs are quite different, see "There is a word" vs " There is a word".

**Comment by kanishkamisra** [comment]
This is "feature" of GPT2 where it treats tokens differently based on whether there's a space in front of them. I am assuming its Byte-pair encoding mechanism hasn't seen "Banana" as the first word too often during training and hence it splits it. The correct way would be to input the text without the space in the beginning! I will make this more clear as a warning/documentation!
