### ISSUE TITLE
Installing with conda

### ISSUE THREAD

**Issue by linghjorten** [kanishkamisra/minicons#25]
Thank you for providing this package which works well for me. I have been using it in a Jupyter notebook but I encountered some problems when trying to use it in an anaconda virtual environment.

I tried to pip install minicons in the virtual environment, but it results in the kernel crashing. Is there a way to conda install minicons?

**Comment by kanishkamisra** [comment]
Hi @linghjorten thanks for raising this concern -- could I ask you for more details about how you set up the virtual environment (version, etc.) or if you see any error message? Also did you run the pip install command through jupyter or before running the `jupyter notebook` command in the shell?

**Comment by linghjorten** [comment]
Hi @kanishkamisra! Thank you for your swift response. After reading your comment, I tried closing the jupyter notebook, pip installed again in the shell and now it runs well in the virtual environment as well.

Sorry for the inconvenience and thanks for a nice package!

**Comment by kanishkamisra** [comment]
Oh great - no worries! Glad you find it useful!
