### ISSUE TITLE
seq_score vs sequence_score vs compute_stats

### ISSUE THREAD

**Issue by bnicenboim** [kanishkamisra/minicons#6]
Hi,
I was giving a try to minicons again. I just installed it using pip, but I'm not sure if that's the latest version.

In the readme file `scorer` shows that it allows for `sequence_score`, in the website [minicons.kanishka.website](https://minicons.kanishka.website/) there is `compute_stats`, but in my version I only have `seq_score`. Have I installed the latest version?

**Comment by kanishkamisra** [comment]
I think you might want to update it! The current version should be 0.2.3. And the demonstration in the readme is the latest one -- I will need to update the website soon, haha! 

Also, `sequence_score`, which is the version you might want to use simply combines `compute_stats` and `prepare_text` along with some other cosmetic-level code to return an output with the right format.

Thanks for bringing this to my attention and sorry for all the confusion!

**Comment by kanishkamisra** [comment]
@bnicenboim feel free to reopen this issue if you still have questions -- I should not have closed it so quickly (my bad)
