### ISSUE TITLE
Upgrading Pandas dependency to 2.2.0

### ISSUE THREAD

**Issue by nikitas-theo** [kanishkamisra/minicons#65]
Hello, and thanks for all the work that is going into this project. 

I was just wondering if it's possible to upgrade pandas to 2.2.0, (right now it seems the requirement is pandas<2.0.0). The reason is it doesn't work very well with Python=3.12, having no available wheels, and also causing other dependency issues and downgrading of packages for its installation. It would make it (at least for me) a lot easier to use the package and integrate it to an existing code base. 

Cheers

**Comment by kanishkamisra** [comment]
Oh thanks for the recommendation -- this makes sense! I will change it :)

**Comment by kanishkamisra** [comment]
just updated it on pypi! thanks again for the recommendation :)

**Comment by nikitas-theo** [comment]
Wow it installed flawlessly after the update, thanks a lot!
Is there any reason for not adding something like pandas>=1.5.3 btw? instead of fixing it on pandas==2.2.0 
In any case, it woks for me.

(unrelated, but just in case you are not aware I think the link to https://minicons.kanishka.website/ on the sidebar is not working)

Thanks again :)
